image: wagnerstephan/bitbucket-git-ftp:latest

pipelines:
  custom:
    init:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm run test
          - git reset --hard
          - git ftp init -u "$FTP_USERNAME" -p "$FTP_PASSWORD" ftp://$FTP_HOST
    deploy:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm run test
          - git reset --hard
          - git ftp init -u "$FTP_USERNAME" -p "$FTP_PASSWORD" ftp://$FTP_HOST
  branches:
    master:
    - step:
        name: Deploy production
        deployment: production
        caches:
          - node
        script:
          - npm install
          - npm run test
          - git reset --hard
          - git ftp init -u "$FTP_USERNAME" -p "$FTP_PASSWORD" ftp://$FTP_HOST
